replicas: 1
image:
  repository: 180942010314.dkr.ecr.us-east-1.amazonaws.com/dev/broker-wizard
  tag: dev-6e7ce58
env: []
configMap:
  enabled: true
  data:
    NODE_ENV: development
    BE_SERVER: http://be-server.dev.svc.cluster.local:8080
    REDIS_HOST: "redis-master"
    REDIS_PORT: '6379'
envFrom:
  enabled: true
  configMapRef: broker-wizard-cm
  secretRef: ''
virtualService:
  enabled: true
  hosts:
  - wizard-dev.healthlucid.com
  gateways:
  - hl-gateway
  http:
  - matchUriPrefix: /
    routePort: 4444
