{{- if .Values.statefulset.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "microservice.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "microservice.fullname" . }}
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      {{- include "microservice.labels" . | nindent 8 }}

  template:
    metadata:
      labels:
        {{- include "microservice.labels" . | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}

          {{- if .Values.redis.args }}
          args:
{{ toYaml .Values.redis.args | nindent 12 }}
          {{- end }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          {{- if .Values.redis.env }}
          env:
{{ toYaml .Values.redis.env | nindent 12 }}
          {{- end }}

          {{- if .Values.redis.envFrom.enabled }}
          envFrom:
            {{- if .Values.redis.envFrom.configMapRef }}
            - configMapRef:
                name: {{ .Values.redis.envFrom.configMapRef }}
            {{- end }}
            {{- if .Values.redis.envFrom.secretRef }}
            - secretRef:
                name: {{ .Values.redis.envFrom.secretRef }}
            {{- end }}
          {{- end }}

          volumeMounts:
            - name: redis-data
              mountPath: /data

  {{- if .Values.redis.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: redis-data
        labels:
          {{- include "microservice.labels" . | nindent 10 }}
      spec:
        accessModes:
          - {{ .Values.redis.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size }}
        {{- if .Values.redis.persistence.storageClass }}
        storageClassName: {{ .Values.redis.persistence.storageClass }}
        {{- end }}
  {{- end }}

{{- end }}
