replicas: 1

image:
  repository: 180942010314.dkr.ecr.us-east-1.amazonaws.com/dev/ai-server
  tag: "v1.0.0-dev"
  pullPolicy: IfNotPresent

deployment:
  enabled: true

serviceaccount:
  enabled: true

service:
  enabled: true
  type: ClusterIP
  port: 5050
  targetPort: 5050

statefulset:
  enabled: false

containerPort: 5050

env: []

configMap:
  enabled: true
  data:
    BE_SERVER: "http://be-server.dev.svc.cluster.local:8080"
    REDIS_HOST: "redis-master"
    REDIS_PORT: "6379"

envFrom:
  enabled: false
  configMapRef: ""
  secretRef: ""

# Probes configuration
probes:
  livenessProbe:
    enabled: true
    path: /ai-services/v1/heartbeat
    port: 5050
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  readinessProbe:
    enabled: true
    path: /ai-services/v1/heartbeat
    port: 5050
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

# Enable Istio VirtualService
virtualService:
  enabled: true
  hosts:
    - ai-server-dev.healthlucid.com
  gateways:
    - hl-gateway
  http:
    - matchUriPrefix: /
      routePort: 5050

# Enable matching DestinationRule (empty policy = default)
destinationRule:
  enabled: true
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

# Enable mTLS for this workload
peerAuthentication:
  enabled: true
  mtlsMode: STRICT
  portLevelMtlsEnabled: true
  portLevelMtls:
    5050:
      mode: STRICT
