replicas: 1

deployment:
  enabled: true

serviceaccount:
  enabled: true

service:
  enabled: true
  type: ClusterIP
  port: 5050
  targetPort: 5050

statefulset:
  enabled: false

containerPort: 5050

# Probes configuration
probes:
  livenessProbe:
    enabled: true
    path: /ai-services/v1/heartbeat
    port: 5050
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  readinessProbe:
    enabled: true
    path: /ai-services/v1/heartbeat
    port: 5050
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

# Enable matching DestinationRule (empty policy = default)
destinationRule:
  enabled: true
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

# Enable mTLS for this workload
peerAuthentication:
  enabled: true
  mtlsMode: STRICT
  portLevelMtlsEnabled: true
  portLevelMtls:
    5061:
      mode: STRICT
