replicas: 1

image:
  repository: 180942010314.dkr.ecr.us-east-1.amazonaws.com/dev/benefit-buddy
  tag: "v1.0.2-dev"
  pullPolicy: IfNotPresent

deployment:
  enabled: true

serviceaccount:
  enabled: true

service:
  type: ClusterIP
  port: 4040
  targetPort: 4040

statefulset:
  enabled: false

containerPort: 4040

env: []

configMap:
  enabled: true
  data:
    NODE_ENV: "development"
    BE_SERVER: "http://be-server.dev.svc.cluster.local:8080"
    AI_SERVER: "http://ai-server.dev.svc.cluster.local:5050"

envFrom:
  enabled: false
  configMapRef: ""
  secretRef: ""

# Probes configuration
probes:
  livenessProbe:
    enabled: true
    path: /
    port: 4040
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  readinessProbe:
    enabled: true
    path: /
    port: 4040
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

# Enable Istio VirtualService
virtualService:
  enabled: true
  hosts:
    - buddy-dev.healthlucid.com
  gateways:
    - hl-gateway
  http:
    - matchUriPrefix: /
      routePort: 4040

# Enable matching DestinationRule (empty policy = default)
destinationRule:
  enabled: true
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

# Enable mTLS for this workload
peerAuthentication:
  enabled: true
  mtlsMode: STRICT
  portLevelMtlsEnabled: true
  portLevelMtls:
    4040:
      mode: STRICT
