configMap:
  enabled: false
  data: {}

redis:
  # Toggle Redis on/off
  enabled: true

  # How many Redis pods (standalone)
  replicaCount: 1

  # Persistence settings
  persistence:
    enabled:      true
    accessMode:   ReadWriteOnce
    size:         8Gi
    storageClass: ""           # leave blank for default
