{{- if .Values.serviceaccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "microservice.fullname" . }}-sa
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
{{- end }}
