apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: healthlucid-root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/elbaza-devops/healthlucid-gitops.git
    targetRevision: HEAD
    path: namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
