replicas: 1

deployment:
  enabled: true

serviceaccount:
  enabled: true

service:
  enabled: true
  type: ClusterIP
  port: 8080
  targetPort: 8080

statefulset:
  enabled: false

containerPort: 8080

# Probes configuration
probes:
  livenessProbe:
    enabled: true
    path: /xlucid-services/v1/heartbeat.json
    port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  readinessProbe:
    enabled: true
    path: /xlucid-services/v1/heartbeat.json
    port: 8080
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

destinationRule:
  enabled: true
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

# Enable mTLS for this workload
peerAuthentication:
  enabled: true
  mtlsMode: STRICT
  portLevelMtlsEnabled: true
  portLevelMtls:
    8080:
      mode: STRICT

