replicas: 1

deployment:
  enabled: true

serviceaccount:
  enabled: true

service:
  enabled: true
  type: ClusterIP
  port: 4444
  targetPort: 4444

statefulset:
  enabled: false

containerPort: 4444

# Probes configuration
probes:
  livenessProbe:
    enabled: true
    path: /
    port: 4444
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  readinessProbe:
    enabled: true
    path: /
    port: 4444
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

# Enable matching DestinationRule (empty policy = default)
destinationRule:
  enabled: true
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

# Enable mTLS for this workload
peerAuthentication:
  enabled: true
  mtlsMode: STRICT
  portLevelMtlsEnabled: true
  portLevelMtls:
    4444:
      mode: STRICT

