configMap:
  enabled: false
  data: {}

deployment:
  enabled: false

service:
  enabled: true
  port:       6379
  targetPort: 6379

serviceaccount:
  enabled: false

statefulset:
  enabled: true

redis:
  # Toggle Redis on/off
  enabled: true

  # How many Redis pods (standalone)
  replicaCount: 1

  # Container image for Redis
  image:
    repository: bitnami/redis
    tag:        "8.0.3"
    pullPolicy: IfNotPresent
    pullSecret: ""

  # Override Redis container args if needed (e.g. Sentinel flags)
  args: []

  # Extra env vars (e.g. you could pull in MASTER_HOST here)
  # env: []
  env:
    - name: REDIS_PASSWORD
      value: ""
    - name: ALLOW_EMPTY_PASSWORD
      value: "yes"

  # Use envFrom to pull in all keys from a Secret or ConfigMap
  envFrom:
    enabled: false
    configMapRef: ""
    secretRef:   "redis-master-secret"

  # Persistence settings
  persistence:
    enabled:      true
    accessMode:   ReadWriteOnce
    size:         8Gi
    storageClass: ""           # leave blank for default

# Istio traffic rules disabled by default
virtualService:
  enabled: false
  hosts: []
  gateways: []
  http: []

destinationRule:
  enabled: true
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

# Enable mTLS for this workload
peerAuthentication:
  enabled: true
  mtlsMode: STRICT
  portLevelMtlsEnabled: false
  portLevelMtls:
    6379:
      mode: STRICT
