replicas: 1

image:
  repository: 180942010314.dkr.ecr.us-east-1.amazonaws.com/dev/hl-admin
  tag: "v1.0.2-dev"
  pullPolicy: IfNotPresent

deployment:
  enabled: true

serviceaccount:
  enabled: true

service:
  enabled: true
  type: ClusterIP
  port: 3181
  targetPort: 3181

statefulset:
  enabled: false

containerPort: 3181

env: []

configMap:
  enabled: true
  data:
    NODE_ENV: "development"
    BE_SERVER: "http://be-server.dev.svc.cluster.local:8080"
    REDIS_HOST: "redis-master"
    REDIS_PORT: "6379"

envFrom:
  enabled: false
  configMapRef: ""
  secretRef: ""

# Probes configuration
probes:
  livenessProbe:
    enabled: true
    path: /
    port: 3181
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  readinessProbe:
    enabled: true
    path: /
    port: 3181
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

# Enable Istio VirtualService
virtualService:
  enabled: true
  hosts:
    - admin-dev.healthlucid.com
  gateways:
    - hl-gateway
  http:
    - matchUriPrefix: /
      routePort: 3181

# Enable matching DestinationRule (empty policy = default)
destinationRule:
  enabled: true
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

# Enable mTLS for this workload
peerAuthentication:
  enabled: true
  mtlsMode: STRICT
  portLevelMtlsEnabled: true
  portLevelMtls:
    3181:
      mode: STRICT
